// <auto-generated />
using System;
using System.Net;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230911194540_FileStorage")]
    partial class FileStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Main.BannedEmail", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.HasKey("Email");

                    b.ToTable("BannedEmail");
                });

            modelBuilder.Entity("API.Models.Main.BannedIp", b =>
                {
                    b.Property<string>("IpV4")
                        .HasColumnType("text");

                    b.HasKey("IpV4");

                    b.ToTable("BannedIp");
                });

            modelBuilder.Entity("API.Models.Main.Like", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("TorrentId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "TorrentId");

                    b.HasIndex("TorrentId");

                    b.ToTable("Like");
                });

            modelBuilder.Entity("API.Models.Main.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeSent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("API.Models.Main.Peer", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("TorrentId")
                        .HasColumnType("integer");

                    b.Property<int>("PeerType")
                        .HasColumnType("integer");

                    b.Property<IPAddress>("IpV4")
                        .IsRequired()
                        .HasColumnType("inet");

                    b.HasKey("UserId", "TorrentId", "PeerType");

                    b.HasIndex("TorrentId");

                    b.ToTable("Peer");
                });

            modelBuilder.Entity("API.Models.Main.Ratio", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("LeechingBytes")
                        .HasColumnType("integer");

                    b.Property<int>("SeedingBytes")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Ratio");
                });

            modelBuilder.Entity("API.Models.Main.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("API.Models.Main.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TagId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("API.Models.Main.Torrent", b =>
                {
                    b.Property<int>("TorrentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TorrentId"));

                    b.Property<string>("DescriptionFilePath")
                        .HasColumnType("text");

                    b.Property<int?>("DownloadAmount")
                        .HasColumnType("integer");

                    b.Property<string>("ImageFilePath")
                        .HasColumnType("text");

                    b.Property<int?>("LikeAmount")
                        .HasColumnType("integer");

                    b.Property<string>("MagnetLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SizeBytes")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TorrentCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("TorrentFilePath")
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TorrentId");

                    b.HasIndex("TorrentCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Torrent");
                });

            modelBuilder.Entity("API.Models.Main.TorrentCategory", b =>
                {
                    b.Property<int>("TorrentCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TorrentCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TorrentCategoryId");

                    b.ToTable("TorrentCategory");
                });

            modelBuilder.Entity("API.Models.Main.TorrentTag", b =>
                {
                    b.Property<int>("TorrentId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<string>("TagValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TorrentId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TorrentTag");
                });

            modelBuilder.Entity("API.Models.Main.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicFilePath")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("API.Models.Main.Like", b =>
                {
                    b.HasOne("API.Models.Main.Torrent", "Torrent")
                        .WithMany("LikedUsers")
                        .HasForeignKey("TorrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Main.User", "User")
                        .WithMany("LikedTorrents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torrent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Main.Notification", b =>
                {
                    b.HasOne("API.Models.Main.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Main.Peer", b =>
                {
                    b.HasOne("API.Models.Main.Torrent", "Torrent")
                        .WithMany("Peers")
                        .HasForeignKey("TorrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Main.User", "User")
                        .WithMany("Peers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torrent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Main.Ratio", b =>
                {
                    b.HasOne("API.Models.Main.User", "User")
                        .WithOne("Ratio")
                        .HasForeignKey("API.Models.Main.Ratio", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Main.Torrent", b =>
                {
                    b.HasOne("API.Models.Main.TorrentCategory", "TorrentCategory")
                        .WithMany("Torrents")
                        .HasForeignKey("TorrentCategoryId");

                    b.HasOne("API.Models.Main.User", "User")
                        .WithMany("UploadedTorrents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TorrentCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Main.TorrentTag", b =>
                {
                    b.HasOne("API.Models.Main.Tag", "Tag")
                        .WithMany("TorrentTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Main.Torrent", "Torrent")
                        .WithMany("TorrentTags")
                        .HasForeignKey("TorrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Torrent");
                });

            modelBuilder.Entity("API.Models.Main.User", b =>
                {
                    b.HasOne("API.Models.Main.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("API.Models.Main.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("API.Models.Main.Tag", b =>
                {
                    b.Navigation("TorrentTags");
                });

            modelBuilder.Entity("API.Models.Main.Torrent", b =>
                {
                    b.Navigation("LikedUsers");

                    b.Navigation("Peers");

                    b.Navigation("TorrentTags");
                });

            modelBuilder.Entity("API.Models.Main.TorrentCategory", b =>
                {
                    b.Navigation("Torrents");
                });

            modelBuilder.Entity("API.Models.Main.User", b =>
                {
                    b.Navigation("LikedTorrents");

                    b.Navigation("Notifications");

                    b.Navigation("Peers");

                    b.Navigation("Ratio")
                        .IsRequired();

                    b.Navigation("UploadedTorrents");
                });
#pragma warning restore 612, 618
        }
    }
}
